### ISSUE TITLE
Двоятся индикаторы на графике если они были созданы без имени

### ISSUE THREAD

**Issue by ak40u** [AlexWan/OsEngine#10]
Раньше у индикаторов был конструктор, который позволял создать объект без имени. Если мы создавали больше 1 объекта без имени, то возникала ошибка каста. 
Я добавил во все индикаторы, где не было Name Name = new uuid.
Это исправило ошибку каста, но появилась новая ошибка.
Теперь каждый раз при запуске тестера у нас создается новый набор индикаторов, если они были созданы с uuid, т.к. у них нет статичных имен.

**Comment by ak40u** [comment]
Предлагаю сделать указание имени индикатора обязательным для пользователя

**Comment by AlexWan** [comment]
хорошо. Давайте так и сделаем. Только давайте я сам этим займусь. Там они кое-где в составных индикаторах используются. Нужно это дело обойти.
