### ISSUE TITLE
Не меняется статус сервера на "Connect" при подключении Робота к Quik

### ISSUE THREAD

**Issue by ak40u** [AlexWan/OsEngine#11]
Quik 7.5.0.72 импортирую настройки infoOSA.wnd
Включаю передачу данных в сервисе.
Добавляю в таблицу Securities бумагу Сбербанк
Запускаю Os.Trader
Открываю Сервера
Жму подключить.

Статус сервера не меняется на Connect, хотя в логах есть события Connect.

![quik](https://cloud.githubusercontent.com/assets/696468/26775389/68c5a22e-49dd-11e7-879e-301661ee833c.jpg)

**Comment by AlexWan** [comment]
Нужно чтобы пошли данные из таблицы всех сделок. Пока этого не произойдёт, коннектор не активируется.
