### ISSUE TITLE
IndexOutOfRangeException в массиве date при выводе All Deals в ДДЕ

### ISSUE THREAD

**Issue by ak40u** [AlexWan/OsEngine#12]
Если добавить вывод сделок из таблицы All Deals по Сберу в ДДЕ, то Os.Trader ругается:
System.IndexOutOfRangeException: Index was outside the bounds of the array. at OsEngine.Market.Servers.Quik.QuikDde.TradesUpdated(Int64 id, Object[,] table) in \OsEngine\project\OsEngine\Market\Servers\Quik\QuikDde.cs:line 285

![quik - date range](https://cloud.githubusercontent.com/assets/696468/26775721/c6daebe8-49de-11e7-9892-6a5e93e0157e.jpg)

**Comment by ak40u** [comment]
Дело оказалось в локали. Поменял на русскую и в date стало 3 элемента. Добавлю в код проверку на размер массива.

**Comment by AlexWan** [comment]
хорошо.
