### ISSUE TITLE
Ошибка при сборке проекта

### ISSUE THREAD

**Issue by spvik** [AlexWan/OsEngine#3]
Добрый день, попробовал собрать скаченный проект, выдает ошибку при компиляции, 
Не удается получить путь файла для библиотеки типа "8252879c-6e32-4322-a38d-8eba54e52595" версии 1.0. Библиотека не зарегистрирована. (Исключение из HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))	OsEngine (OsEngine\OsEngine)			
и так же не находит библиотеки SmartCom, SmartCom - Обязательно устанавливать?

**Comment by ak40u** [comment]
Установите смартком. Все должно работать из коробки в VS.

**Comment by spvik** [comment]
Установил смартком, все заработало
