### ISSUE TITLE
OsChart жрет ЦП

### ISSUE THREAD

**Issue by ak40u** [AlexWan/OsEngine#33]
Привет. 
OsEngine версии 1.0.0.0 с одной панелью подключенный через DDE к Квику потребляет слишком много ЦП и оперативки.
![image](https://user-images.githubusercontent.com/696468/29808820-45627a66-8ca2-11e7-9bc4-3d81f7855078.png)
Если выключить прорисовку, то ресурсы освобождаются.

**Comment by AlexWan** [comment]
Как раз этим занимаюсь, но не по этой причине.
Однако такого точно не будет. 
К выходным сделаю.
Перебираю механизмы прорисовки всей платформы.
