### ISSUE TITLE
Site URL should have forward slashes

### ISSUE THREAD

**Issue by kamalx** [AlexWan/OsEngine#38]
The site URL, mentioned in repo description on top, with backward slashes doesn't work (at least on Chrome on Mac OS X; and I suspect in other popular browser-platform combinations). 

Screenshot for ref:
![image](https://user-images.githubusercontent.com/94972/35764087-bad5d784-08df-11e8-889f-c5cb24bdfdf8.png)

It needs to be `http://o-s-a.net/`

**Comment by AlexWan** [comment]
Thanks
