### ISSUE TITLE
Минимальное значение на графике

### ISSUE THREAD

**Issue by RusinDmitrii** [AlexWan/OsEngine#49]
Здравствуйте Алексей,
https://github.com/AlexWan/OsEngine/blob/cd6941d7a7f6f98eb5b103448e32fd12f98cb41b/project/OsEngine/Charts/CandleChart/ChartPainter.cs#L5316

Например для индикатора дельты (разницы между объемом покупки и продажи) это условие делает индикатор не информативным визуально, т.к. отрицательные значения на нем перестают отображаться

**Comment by AlexWan** [comment]
сделано
