### ISSUE TITLE
Сжимаются свечи на чарте в тестере

### ISSUE THREAD

**Issue by ak40u** [AlexWan/OsEngine#9]
Привет.
При тестировании робота Strategy19-27 на котировках сбербанка h1 из os.data через 10-20 свечей после старта теста чарт сжимает график и становится ничего не видно.
Если приблизить свечи вручную, то они очень тонкие.
Данные в сете выглядят нормально.

![prev](https://cloud.githubusercontent.com/assets/696468/26764281/a06e140c-496c-11e7-8877-65e2def69e23.jpg)
![after](https://cloud.githubusercontent.com/assets/696468/26764282/a07344cc-496c-11e7-9df6-12f71e4a14ab.jpg)
[Debug.zip](https://github.com/AlexWan/OsEngine/files/1050611/Debug.zip)

**Comment by ak40u** [comment]
Индикаторы робота:
`            volume = 1;
            TabCreate(BotTabType.Simple);
            _tab = TabsSimple[0];

            _bol_10 = new Bollinger("bol1",false);
            _bol_10.Lenght = 10;
            _bol_10.Deviation = 5;
            _bol_10 = (Bollinger)_tab.CreateCandleIndicator(_bol_10, "prime");
            _bol_10.Save();


            _bol_9 = new Bollinger("bol2", false);
            _bol_9.Lenght = 9;
            _bol_9.Deviation = 2;
            _bol_9 = (Bollinger)_tab.CreateCandleIndicator(_bol_9, "prime");
            _bol_9.Save();


            _ema9 = new MovingAverage("ema1", false);
            _ema9.Lenght = 9;

            _ema9 = (MovingAverage)_tab.CreateCandleIndicator(_ema9, "Prime");
            _ema9.Save();

            _atr_77 = new Atr("atr1", false);
            _atr_77.Lenght = 77;
            _atr_77 = (Atr)_tab.CreateCandleIndicator(_atr_77, "Prime");
            _atr_77.Save();`

**Comment by AlexWan** [comment]
Atr нужно разместить на новой области чарта, т.к. оно имеет очень малые значения. Вместо "Prime" введите другое имя для области.
Оно сжимается т.к. нужно индикатор уместить тоже на чарте. Если мне память не изменяет, у Квика того же также происходит...
